@baseUrl = http://localhost:3001/api

#Categories

# @name getAllCategories
GET {{baseUrl}}/categories?_page=0&_limit=20
###

# @name getAllProducts
GET {{baseUrl}}/products?_page=0&_limit=1&price_gte=500

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Loa"
}

###

# @name addNewCategory
PATCH {{baseUrl}}/categories/2
Content-Type: application/json

{
    "name": "Laptop"
}

###

# @name addNewCategory
DELETE {{baseUrl}}/categories/6